system:
  router:
    port: 4568
  database:
    path: yaus.db
hardcoded:
  error:
  - key: '999'
    url: https://github.com/FideTech/yaus/wiki
  - key: '888'
    url: https://github.com/FideTech/yaus/wiki/888
  info:
  - key: google
    url: https://google.com
  - key: duck
    url: https://duckduckgo.com
